// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1bIt5aoWn3GU5A13T-kV_g6VJ8-pmETo',
    appId: '1:612958493049:android:ba7cd7211360ce4a2ab7a8',
    messagingSenderId: '612958493049',
    projectId: 'fir-auth-tutorial-5fe22',
    storageBucket: 'fir-auth-tutorial-5fe22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1Ro3dQVr2xWzR1YZunBdP2muTZ5HQr8',
    appId: '1:612958493049:ios:cc8545f75a868da82ab7a8',
    messagingSenderId: '612958493049',
    projectId: 'fir-auth-tutorial-5fe22',
    storageBucket: 'fir-auth-tutorial-5fe22.appspot.com',
    androidClientId: '612958493049-3ap8erbd7hj7vug4eu6nklpqp0ponae8.apps.googleusercontent.com',
    iosClientId: '612958493049-2snn4am8fk7o6jm48n5ce0rvkvau9c2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterFirebaseAuth',
  );
}
